# Automatically builds the project and runs any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defense
# against bad commits.

name: build
on:
  # Don't build if only text-based files were changed.
  # Prevents waiting for unnecessary checks/actions
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    strategy:
      matrix:
        java: [
          21 # Latest Java LTS & minimum supported by Minecraft
        ]
        # and run on the latest dists of Linux, MacOS, and Windows
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: build
        run: ./gradlew build --info --stacktrace

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            build/libs/
            build/devlibs/
            !build/devlibs/*-sources.jar