name: gradle_dependency_submission

on:
  # Don't build if only text-based files were changed.
  # Prevents waiting for unnecessary checks/actions
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

# remainder of the file is copied from https://github.com/marketplace/actions/build-with-gradle#the-dependency-submission-action
permissions:
  contents: write

jobs:
  dependency-submission:
    strategy:
      matrix:
        java: [
          21 # Latest Java LTS & minimum supported by Minecraft
        ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4